In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv('data.csv')
print(ds.to_string())

                                                  name     company  year          Price    kms_driven fuel_type
0                 Hyundai Santro Xing XO eRLX Euro III     Hyundai  2007         80,000    45,000 kms    Petrol
1                              Mahindra Jeep CL550 MDI    Mahindra  2006       4,25,000        40 kms    Diesel
2                           Maruti Suzuki Alto 800 Vxi      Maruti  2018  Ask For Price    22,000 kms    Petrol
3               Hyundai Grand i10 Magna 1.2 Kappa VTVT     Hyundai  2014       3,25,000    28,000 kms    Petrol
4                     Ford EcoSport Titanium 1.5L TDCi        Ford  2014       5,75,000    36,000 kms    Diesel
5                     Ford EcoSport Titanium 1.5L TDCi        Ford  2015  Ask For Price    59,000 kms    Diesel
6                                            Ford Figo        Ford  2012       1,75,000    41,000 kms    Diesel
7                                          Hyundai Eon     Hyundai  2013       1,90,000    25,000 kms    Petrol
8                     Ford EcoSport Ambiente 1.5L TDCi        Ford  2016       8,30,000    24,530 kms    Diesel
9                       Maruti Suzuki Alto K10 VXi AMT      Maruti  2015       2,50,000    60,000 kms    Petrol
10                         Skoda Fabia Classic 1.2 MPI       Skoda  2010       1,82,000    60,000 kms    Petrol
11                          Maruti Suzuki Stingray VXi      Maruti  2015       3,15,000    30,000 kms    Petrol
12                         Hyundai Elite i20 Magna 1.2     Hyundai  2014       4,15,000    32,000 kms    Petrol
13                          Mahindra Scorpio SLE BS IV    Mahindra  2015       3,20,000    48,660 kms    Diesel
14                Hyundai Santro Xing XO eRLX Euro III     Hyundai  2007         80,000    45,000 kms    Petrol
15                             Mahindra Jeep CL550 MDI    Mahindra  2006       4,25,000        40 kms    Diesel
16                                             Audi A8        Audi  2017      10,00,000     4,000 kms    Petrol
17                                             Audi Q7        Audi  2014       5,00,000    16,934 kms    Diesel
18                                Mahindra Scorpio S10    Mahindra  2016       3,50,000    43,000 kms    Diesel
19                              Maruti Suzuki Alto 800      Maruti  2014       1,60,000    35,550 kms    Petrol
20                                Mahindra Scorpio S10    Mahindra  2016       3,50,000    43,000 kms    Diesel
21                                Mahindra Scorpio S10    Mahindra  2016       3,10,000    39,522 kms    Diesel
22                          Maruti Suzuki Alto 800 Vxi      Maruti  2015         75,000    39,000 kms    Petrol
23                              Hyundai i20 Sportz 1.2     Hyundai  2012       1,00,000    55,000 kms    Petrol
24                              Hyundai i20 Sportz 1.2     Hyundai  2012       1,00,000    55,000 kms    Petrol
25                              Hyundai i20 Sportz 1.2     Hyundai  2012       1,00,000    55,000 kms    Petrol
26                           Maruti Suzuki Alto 800 Lx      Maruti  2017       1,90,000    72,000 kms    Petrol
27                     Maruti Suzuki Vitara Brezza ZDi      Maruti  2016       2,90,000    15,975 kms    Diesel
28                               Maruti Suzuki Alto LX      Maruti  2008         95,000    70,000 kms    Petrol
29                                  Mahindra Bolero DI    Mahindra  2017       1,80,000    23,452 kms    Diesel
30                       Maruti Suzuki Swift Dzire ZDi      Maruti  2014       3,85,000    35,522 kms    Diesel
31                            Mahindra Scorpio S10 4WD    Mahindra  2015       2,50,000    48,508 kms    Diesel
32                       Maruti Suzuki Swift Vdi BSIII      Maruti  2017       1,80,000    15,487 kms    Petrol
33                    Maruti Suzuki Wagon R VXi BS III      Maruti  2013       1,05,000    39,000 kms    Petrol
34                     Maruti Suzuki Wagon R VXi Minor      Maruti  2013       1,05,000    39,000 kms    Petrol
35                     Toyota Innova 2.0 G 8 STR BS IV      Toyota  2012       6,50,000    82,000 kms    Diesel
36                             Renault Lodgy 85 PS RXL     Renault  2018       6,89,999    20,000 kms    Diesel
37                  Skoda Yeti Ambition 2.0 TDI CR 4x2       Skoda  2012       4,48,000    68,000 kms    Diesel
38                      Maruti Suzuki Baleno Delta 1.2      Maruti  2017       5,49,000    32,000 kms    Diesel
39               Renault Duster 110 PS RxZ Diesel Plus     Renault  2012       5,01,000    38,000 kms    Diesel
40                     Renault Duster 85 PS RxE Diesel     Renault  2013       4,89,999    27,000 kms    Diesel
41                                 Honda City 1.5 S MT       Honda  2011       2,80,000    33,000 kms    Petrol
42                      Maruti Suzuki Alto K10 VXi AMT      Maruti  2015       2,50,000    60,000 kms    Petrol
43                                 Maruti Suzuki Dzire      Maruti  2013       3,49,999    46,000 kms    Diesel
44                                         Honda Amaze       Honda  2013       2,84,999    46,000 kms    Diesel
45                           Honda Amaze 1.5 SX i DTEC       Honda  2015       3,45,000    36,000 kms    Diesel
46                                          Honda City       Honda  2015       4,99,999    55,000 kms    Petrol
47                                    Datsun Redi GO S      Datsun  2017       2,35,000    16,000 kms    Petrol
48                            Maruti Suzuki SX4 ZXI MT      Maruti  2010       2,49,999    36,000 kms    Petrol
49             Mitsubishi Pajero Sport Limited Edition  Mitsubishi  2015      14,75,000    47,000 kms    Diesel
50                                  Mahindra Bolero DI    Mahindra  2017       1,80,000    23,452 kms    Diesel
51                       Maruti Suzuki Swift Dzire ZDi      Maruti  2014       3,85,000    35,522 kms    Diesel
52                            Mahindra Scorpio S10 4WD    Mahindra  2015       2,50,000    48,508 kms    Diesel
53                       Maruti Suzuki Swift Vdi BSIII      Maruti  2017       1,80,000    15,487 kms    Petrol
54                    Maruti Suzuki Wagon R VXi BS III      Maruti  2013       1,05,000    39,000 kms    Petrol
55                     Maruti Suzuki Wagon R VXi Minor      Maruti  2013       1,05,000    39,000 kms    Petrol
56                                Mahindra Scorpio S10    Mahindra  2015       3,95,000    35,000 kms    Diesel
57               Maruti Suzuki Swift VXi 1.2 ABS BS IV      Maruti  2017       2,20,000    30,874 kms    Petrol
58                                   Honda City ZX CVT       Honda  2017       1,70,000    15,000 kms    Diesel
59                      Maruti Suzuki Wagon R LX BS IV      Maruti  2013         85,000    29,685 kms    Petrol
60                                           Ford Figo        Ford  2012       1,75,000    41,000 kms    Diesel
61                                         Hyundai Eon     Hyundai  2013       1,90,000    25,000 kms    Petrol
62                        Tata Indigo eCS LS CR4 BS IV        Tata  2017       2,00,000  1,30,000 kms    Diesel
63                    Ford EcoSport Ambiente 1.5L TDCi        Ford  2016       8,30,000    24,530 kms    Diesel
64                        Tata Indigo eCS LS CR4 BS IV        Tata  2017       2,00,000  1,30,000 kms    Diesel
65                          Mahindra Scorpio SLE BS IV    Mahindra  2012       5,70,000    19,000 kms    Diesel
66                Volkswagen Polo Highline Exquisite P  Volkswagen  2014       3,15,000    60,000 kms    Petrol
67                         Skoda Fabia Classic 1.2 MPI       Skoda  2010       1,82,000    60,000 kms    Petrol
68                          Maruti Suzuki Stingray VXi      Maruti  2015       3,15,000    30,000 kms    Petrol
69                     I want to sell my car Tata Zest           I  2017  Ask For Price           NaN       NaN
70                              Chevrolet Spark LS 1.0   Chevrolet  2010       1,10,000    41,000 kms    Petrol
71                     Renault Duster 110PS Diesel RxZ     Renault  2012       5,01,000    35,000 kms    Diesel
72                                          Honda City       Honda  2015       4,48,999    54,000 kms    Petrol
73                                   Mini Cooper S 1.6        Mini  2013      18,91,111    13,000 kms    Petrol
74                                    Datsun Redi GO S      Datsun  2017       2,35,000    16,000 kms    Petrol
75                    Skoda Fabia 1.2L Diesel Ambiente       Skoda  2011       1,59,500    38,200 kms    Diesel
76                                         Honda Amaze       Honda  2015       3,44,999    22,000 kms    Petrol
77                                         Honda Amaze       Honda  2015       3,44,999    22,000 kms    Petrol
78                                      Renault Duster     Renault  2014       4,49,999    50,000 kms    Diesel
79                                   Mini Cooper S 1.6        Mini  2013      18,91,111    13,500 kms    Petrol
80                                 Mahindra Scorpio S4    Mahindra  2015       8,65,000    30,000 kms    Diesel
81                      Mahindra Scorpio VLX 2WD BS IV    Mahindra  2014       6,99,000    50,000 kms    Diesel
82                                  Mahindra Quanto C8    Mahindra  2013       3,75,000    20,000 kms    Diesel
83                                       Ford EcoSport        Ford  2017       4,89,999    39,000 kms    Petrol
84                                          Honda Brio       Honda  2012       2,24,999    30,000 kms    Petrol
85                     I want to sell my car Tata Zest           I  2017  Ask For Price           NaN       NaN
86        Volkswagen Vento Highline Plus 1.5 Diesel AT  Volkswagen  2019      12,00,000     3,600 kms    Diesel
87                                   Hyundai i20 Magna     Hyundai  2009       1,95,000    32,000 kms    Petrol
88                    Toyota Corolla Altis Diesel D4DG      Toyota  2010       3,51,000    38,000 kms    Diesel
89                     Hyundai Verna Transform SX VTVT     Hyundai  2008       1,60,000    45,000 kms    Petrol
90                     Toyota Corolla Altis Petrol Ltd      Toyota  2009       2,40,000    35,000 kms    Petrol
91                              Honda City 1.5 EXi New       Honda  2005         90,000    50,000 kms    Petrol
92                         Hyundai Elite i20 Magna 1.2     Hyundai  2014       4,15,000    32,000 kms    Petrol
93                    Skoda Fabia 1.2L Diesel Elegance       Skoda  2011       1,55,000    45,863 kms    Diesel
94                                   BMW 3 Series 320i         BMW  2011       6,00,000    60,500 kms    Petrol
95                            Maruti Suzuki A Star Lxi      Maruti  2011       1,89,500    12,500 kms    Petrol
96                                     Toyota Etios GD      Toyota  2013       3,50,000    60,000 kms    Diesel
97                         Ford Figo Diesel EXI Option        Ford  2012       2,10,000    35,000 kms    Diesel
98             Maruti Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2014       3,90,000    35,000 kms    Petrol
99                            Chevrolet Beat LT Diesel   Chevrolet  2012       1,35,000    45,000 kms    Diesel
100                           BMW 7 Series 740Li Sedan         BMW  2009      16,00,000    35,000 kms    Petrol
101                        Mahindra XUV500 W8 AWD 2013    Mahindra  2013       7,01,000    38,000 kms    Diesel
102                              Hyundai i10 Magna 1.2     Hyundai  2014       2,65,000    18,000 kms    Petrol
103                          Hyundai Verna Fluidic New     Hyundai  2015       5,25,000    35,000 kms    Diesel
104                  Maruti Suzuki Swift VXi 1.2 BS IV      Maruti  2013       3,72,000    13,349 kms    Petrol
105                      Maruti Suzuki Ertiga ZXI Plus      Maruti  2016       6,35,000    29,000 kms    Petrol
106                   Ford EcoSport Titanium 1.5L TDCi        Ford  2014       5,50,000    44,000 kms    Diesel
107                           Maruti Suzuki Ertiga Vxi      Maruti  2016       5,75,000    29,000 kms    Petrol
108                           Maruti Suzuki Ertiga VDi      Maruti  2013       4,85,000    42,000 kms    Diesel
109                      Maruti Suzuki Alto LXi BS III      Maruti  2012       1,55,000    14,000 kms    Petrol
110                    Hyundai Grand i10 Asta 1.1 CRDi     Hyundai  2014       3,45,000    49,000 kms    Diesel
111                           Honda Amaze 1.2 S i VTEC       Honda  2014       3,25,000    42,000 kms    Petrol
112                  Hyundai i20 Asta 1.4 CRDI 6 Speed     Hyundai  2012       3,29,500    36,200 kms    Diesel
113                               Ford Figo Diesel EXI        Ford  2014       1,95,000    50,000 kms    Diesel
114               Maruti Suzuki Eeco 5 STR WITH AC HTR      Maruti  2015       2,51,111    55,000 kms    Petrol
115                           Maruti Suzuki Ertiga ZXi      Maruti  2014       5,69,999    45,000 kms    Petrol
116                    Maruti Suzuki Esteem LXi BS III      Maruti  2007         69,999    51,000 kms    Petrol
117                             Maruti Suzuki Ritz VXI      Maruti  2014       2,99,999    19,000 kms    Petrol
118                                Maruti Suzuki Dzire      Maruti  2009       2,20,000    46,000 kms    Petrol
119                             Maruti Suzuki Ritz LDi      Maruti  2013       3,99,999    33,000 kms    Diesel
120                  Maruti Suzuki Swift VXi 1.2 BS IV      Maruti  2013       3,72,000    13,349 kms    Petrol
121                            Maruti Suzuki Dzire VDI      Maruti  2015       4,50,000  1,04,000 kms    Diesel
122                                Toyota Etios Liva G      Toyota  2014       2,70,000    55,000 kms    Petrol
123                        Hyundai i20 Sportz 1.4 CRDI     Hyundai  2011       3,50,000    33,333 kms    Diesel
124                                    Chevrolet Spark   Chevrolet  2012       1,58,400    33,600 kms    Petrol
125                     Maruti Suzuki Alto K10 VXi AMT      Maruti  2017       3,50,000     5,600 kms    Petrol
126                                    Nissan Micra XV      Nissan  2011       1,79,000    41,000 kms    Petrol
127                                Maruti Suzuki Swift      Maruti  2007       1,25,000    70,000 kms    Petrol
128                             Maruti Suzuki Alto 800      Maruti  2018       2,00,000     7,500 kms    Petrol
129                           Honda Amaze 1.5 S i DTEC       Honda  2013       2,99,000    45,000 kms    Diesel
130                         Maruti Suzuki Alto 800 Vxi      Maruti  2015       2,20,000    38,000 kms    Petrol
131                                     Chevrolet Beat   Chevrolet  2015       1,50,000    30,000 kms    Petrol
132                                     Toyota Corolla      Toyota  2009       2,75,000    26,000 kms       NaN
133                                Honda City 1.5 V MT       Honda  2010       2,85,000    35,000 kms    Petrol
134                      Ford EcoSport Trend 1.5L TDCi        Ford  2016       8,30,000    24,330 kms    Diesel
135                               Hyundai i20 Asta 1.2     Hyundai  2009       2,10,000    65,480 kms    Petrol
136            Maruti Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2013       3,40,000    41,000 kms    Petrol
137                                 Tata Indica V2 eLS        Tata  2006         90,000    20,000 kms    Petrol
138                         Maruti Suzuki Alto 800 Lxi      Maruti  2018  Ask For Price    28,028 kms    Petrol
139                        Hindustan Motors Ambassador   Hindustan  2000         70,000  2,00,000 kms    Diesel
140                        Toyota Corolla Altis 1.8 GL      Toyota  2010       2,89,999    70,000 kms    Petrol
141                         Toyota Corolla Altis 1.8 J      Toyota  2012       3,49,999    59,000 kms    Petrol
142                   Toyota Innova 2.5 GX BS IV 7 STR      Toyota  2012       8,49,999    99,000 kms    Diesel
143                   Volkswagen Jetta Highline TDI AT  Volkswagen  2014       7,49,999    46,000 kms    Diesel
144                 Volkswagen Polo Comfortline 1.2L P  Volkswagen  2015       3,99,999     2,800 kms    Petrol
145                                    Volkswagen Polo  Volkswagen  2014       2,74,999    32,000 kms    Petrol
146                                   Mahindra Scorpio    Mahindra  2015       9,84,999    22,000 kms    Diesel
147                                     Renault Duster     Renault  2014       4,49,999    50,000 kms    Diesel
148                                        Honda Amaze       Honda  2015       3,44,999    22,000 kms    Petrol
149                                       Nissan Sunny      Nissan  2012       2,24,999    45,000 kms    Petrol
150                                  Hyundai Elite i20     Hyundai  2018       5,99,999    21,000 kms    Petrol
151                                       Renault Kwid     Renault  2016       2,44,999    11,000 kms    Petrol
152                                     Renault Duster     Renault  2013       3,99,999    41,000 kms    Diesel
153                                      Ford EcoSport        Ford  2017       4,89,999    39,000 kms    Petrol
154                                     Renault Duster     Renault  2014       4,74,999    50,000 kms    Diesel
155                        Mahindra Scorpio VLX Airbag    Mahindra  2011       4,99,999    66,000 kms    Diesel
156                         Maruti Suzuki Alto 800 Lxi      Maruti  2018       3,10,000     3,000 kms    Petrol
157                             Chevrolet Spark LT 1.0   Chevrolet  2010         85,000    45,000 kms    Petrol
158                                 Datsun Redi GO T O      Datsun  2016       2,45,000     7,000 kms    Petrol
159                         Maruti Suzuki Swift RS VDI      Maruti  2010       1,89,500    38,500 kms    Diesel
160                             Fiat Punto Emotion 1.2        Fiat  2012       1,69,500    37,200 kms    Diesel
161                         Maruti Suzuki Swift RS VDI      Maruti  2010       1,59,500    43,200 kms    Diesel
162                                    Toyota Etios GD      Toyota  2013       2,75,000    24,800 kms    Petrol
163                        Hyundai i20 Sportz 1.4 CRDI     Hyundai  2014       3,70,000    60,000 kms    Diesel
164                             Hyundai i10 Sportz 1.2     Hyundai  2010       1,68,000    45,872 kms    Petrol
165                       Chevrolet Beat LT Opt Diesel   Chevrolet  2011       1,50,000    40,000 kms    Diesel
166                           Chevrolet Beat LS Diesel   Chevrolet  2011       1,45,000    45,000 kms    Diesel
167                           Chevrolet Beat LT Diesel   Chevrolet  2012         98,500    38,000 kms    Diesel
168                     Mahindra Scorpio VLX 2WD BS IV    Mahindra  2014       6,99,000    50,000 kms    Diesel
169                                     Tata Indigo CS        Tata  2011         85,000    11,400 kms    Diesel
170                         Toyota Corolla Altis 1.8 J      Toyota  2015       5,75,000    42,000 kms    Petrol
171                                Honda City 1.5 V MT       Honda  2014       5,49,000    39,000 kms    Petrol
172                            Maruti Suzuki Swift VDi      Maruti  2011       2,09,000    47,000 kms    Diesel
173                               Hyundai Eon Era Plus     Hyundai  2013       1,85,000    27,000 kms    Petrol
174                               Mahindra Scorpio S10    Mahindra  2015       9,00,000    97,200 kms    Diesel
175                                    Mahindra XUV500    Mahindra  2014       6,99,999    52,000 kms    Diesel
176                                         Honda Brio       Honda  2012       2,24,999    30,000 kms    Petrol

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [4]:
ds.describe()

              name company  year          Price  kms_driven fuel_type
count          892     892   892            892         840       837
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            13     235   117             35          30       440

In [5]:
ds['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [6]:
#dropping null cells
ds.dropna(inplace=True)

In [7]:
#convert data type of year column object to int
ds['year']= pd.to_numeric(ds['year'], errors='coerce')

In [8]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        837 non-null    object
 1   company     837 non-null    object
 2   year        837 non-null    int64
 3   Price       837 non-null    object
 4   kms_driven  837 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 45.8+ KB

In [9]:
print(ds.to_string())

                                                  name     company  year          Price    kms_driven fuel_type
0                 Hyundai Santro Xing XO eRLX Euro III     Hyundai  2007         80,000    45,000 kms    Petrol
1                              Mahindra Jeep CL550 MDI    Mahindra  2006       4,25,000        40 kms    Diesel
2                           Maruti Suzuki Alto 800 Vxi      Maruti  2018  Ask For Price    22,000 kms    Petrol
3               Hyundai Grand i10 Magna 1.2 Kappa VTVT     Hyundai  2014       3,25,000    28,000 kms    Petrol
4                     Ford EcoSport Titanium 1.5L TDCi        Ford  2014       5,75,000    36,000 kms    Diesel
5                     Ford EcoSport Titanium 1.5L TDCi        Ford  2015  Ask For Price    59,000 kms    Diesel
6                                            Ford Figo        Ford  2012       1,75,000    41,000 kms    Diesel
7                                          Hyundai Eon     Hyundai  2013       1,90,000    25,000 kms    Petrol
8                     Ford EcoSport Ambiente 1.5L TDCi        Ford  2016       8,30,000    24,530 kms    Diesel
9                       Maruti Suzuki Alto K10 VXi AMT      Maruti  2015       2,50,000    60,000 kms    Petrol
10                         Skoda Fabia Classic 1.2 MPI       Skoda  2010       1,82,000    60,000 kms    Petrol
11                          Maruti Suzuki Stingray VXi      Maruti  2015       3,15,000    30,000 kms    Petrol
12                         Hyundai Elite i20 Magna 1.2     Hyundai  2014       4,15,000    32,000 kms    Petrol
13                          Mahindra Scorpio SLE BS IV    Mahindra  2015       3,20,000    48,660 kms    Diesel
14                Hyundai Santro Xing XO eRLX Euro III     Hyundai  2007         80,000    45,000 kms    Petrol
15                             Mahindra Jeep CL550 MDI    Mahindra  2006       4,25,000        40 kms    Diesel
16                                             Audi A8        Audi  2017      10,00,000     4,000 kms    Petrol
17                                             Audi Q7        Audi  2014       5,00,000    16,934 kms    Diesel
18                                Mahindra Scorpio S10    Mahindra  2016       3,50,000    43,000 kms    Diesel
19                              Maruti Suzuki Alto 800      Maruti  2014       1,60,000    35,550 kms    Petrol
20                                Mahindra Scorpio S10    Mahindra  2016       3,50,000    43,000 kms    Diesel
21                                Mahindra Scorpio S10    Mahindra  2016       3,10,000    39,522 kms    Diesel
22                          Maruti Suzuki Alto 800 Vxi      Maruti  2015         75,000    39,000 kms    Petrol
23                              Hyundai i20 Sportz 1.2     Hyundai  2012       1,00,000    55,000 kms    Petrol
24                              Hyundai i20 Sportz 1.2     Hyundai  2012       1,00,000    55,000 kms    Petrol
25                              Hyundai i20 Sportz 1.2     Hyundai  2012       1,00,000    55,000 kms    Petrol
26                           Maruti Suzuki Alto 800 Lx      Maruti  2017       1,90,000    72,000 kms    Petrol
27                     Maruti Suzuki Vitara Brezza ZDi      Maruti  2016       2,90,000    15,975 kms    Diesel
28                               Maruti Suzuki Alto LX      Maruti  2008         95,000    70,000 kms    Petrol
29                                  Mahindra Bolero DI    Mahindra  2017       1,80,000    23,452 kms    Diesel
30                       Maruti Suzuki Swift Dzire ZDi      Maruti  2014       3,85,000    35,522 kms    Diesel
31                            Mahindra Scorpio S10 4WD    Mahindra  2015       2,50,000    48,508 kms    Diesel
32                       Maruti Suzuki Swift Vdi BSIII      Maruti  2017       1,80,000    15,487 kms    Petrol
33                    Maruti Suzuki Wagon R VXi BS III      Maruti  2013       1,05,000    39,000 kms    Petrol
34                     Maruti Suzuki Wagon R VXi Minor      Maruti  2013       1,05,000    39,000 kms    Petrol
35                     Toyota Innova 2.0 G 8 STR BS IV      Toyota  2012       6,50,000    82,000 kms    Diesel
36                             Renault Lodgy 85 PS RXL     Renault  2018       6,89,999    20,000 kms    Diesel
37                  Skoda Yeti Ambition 2.0 TDI CR 4x2       Skoda  2012       4,48,000    68,000 kms    Diesel
38                      Maruti Suzuki Baleno Delta 1.2      Maruti  2017       5,49,000    32,000 kms    Diesel
39               Renault Duster 110 PS RxZ Diesel Plus     Renault  2012       5,01,000    38,000 kms    Diesel
40                     Renault Duster 85 PS RxE Diesel     Renault  2013       4,89,999    27,000 kms    Diesel
41                                 Honda City 1.5 S MT       Honda  2011       2,80,000    33,000 kms    Petrol
42                      Maruti Suzuki Alto K10 VXi AMT      Maruti  2015       2,50,000    60,000 kms    Petrol
43                                 Maruti Suzuki Dzire      Maruti  2013       3,49,999    46,000 kms    Diesel
44                                         Honda Amaze       Honda  2013       2,84,999    46,000 kms    Diesel
45                           Honda Amaze 1.5 SX i DTEC       Honda  2015       3,45,000    36,000 kms    Diesel
46                                          Honda City       Honda  2015       4,99,999    55,000 kms    Petrol
47                                    Datsun Redi GO S      Datsun  2017       2,35,000    16,000 kms    Petrol
48                            Maruti Suzuki SX4 ZXI MT      Maruti  2010       2,49,999    36,000 kms    Petrol
49             Mitsubishi Pajero Sport Limited Edition  Mitsubishi  2015      14,75,000    47,000 kms    Diesel
50                                  Mahindra Bolero DI    Mahindra  2017       1,80,000    23,452 kms    Diesel
51                       Maruti Suzuki Swift Dzire ZDi      Maruti  2014       3,85,000    35,522 kms    Diesel
52                            Mahindra Scorpio S10 4WD    Mahindra  2015       2,50,000    48,508 kms    Diesel
53                       Maruti Suzuki Swift Vdi BSIII      Maruti  2017       1,80,000    15,487 kms    Petrol
54                    Maruti Suzuki Wagon R VXi BS III      Maruti  2013       1,05,000    39,000 kms    Petrol
55                     Maruti Suzuki Wagon R VXi Minor      Maruti  2013       1,05,000    39,000 kms    Petrol
56                                Mahindra Scorpio S10    Mahindra  2015       3,95,000    35,000 kms    Diesel
57               Maruti Suzuki Swift VXi 1.2 ABS BS IV      Maruti  2017       2,20,000    30,874 kms    Petrol
58                                   Honda City ZX CVT       Honda  2017       1,70,000    15,000 kms    Diesel
59                      Maruti Suzuki Wagon R LX BS IV      Maruti  2013         85,000    29,685 kms    Petrol
60                                           Ford Figo        Ford  2012       1,75,000    41,000 kms    Diesel
61                                         Hyundai Eon     Hyundai  2013       1,90,000    25,000 kms    Petrol
62                        Tata Indigo eCS LS CR4 BS IV        Tata  2017       2,00,000  1,30,000 kms    Diesel
63                    Ford EcoSport Ambiente 1.5L TDCi        Ford  2016       8,30,000    24,530 kms    Diesel
64                        Tata Indigo eCS LS CR4 BS IV        Tata  2017       2,00,000  1,30,000 kms    Diesel
65                          Mahindra Scorpio SLE BS IV    Mahindra  2012       5,70,000    19,000 kms    Diesel
66                Volkswagen Polo Highline Exquisite P  Volkswagen  2014       3,15,000    60,000 kms    Petrol
67                         Skoda Fabia Classic 1.2 MPI       Skoda  2010       1,82,000    60,000 kms    Petrol
68                          Maruti Suzuki Stingray VXi      Maruti  2015       3,15,000    30,000 kms    Petrol
70                              Chevrolet Spark LS 1.0   Chevrolet  2010       1,10,000    41,000 kms    Petrol
71                     Renault Duster 110PS Diesel RxZ     Renault  2012       5,01,000    35,000 kms    Diesel
72                                          Honda City       Honda  2015       4,48,999    54,000 kms    Petrol
73                                   Mini Cooper S 1.6        Mini  2013      18,91,111    13,000 kms    Petrol
74                                    Datsun Redi GO S      Datsun  2017       2,35,000    16,000 kms    Petrol
75                    Skoda Fabia 1.2L Diesel Ambiente       Skoda  2011       1,59,500    38,200 kms    Diesel
76                                         Honda Amaze       Honda  2015       3,44,999    22,000 kms    Petrol
77                                         Honda Amaze       Honda  2015       3,44,999    22,000 kms    Petrol
78                                      Renault Duster     Renault  2014       4,49,999    50,000 kms    Diesel
79                                   Mini Cooper S 1.6        Mini  2013      18,91,111    13,500 kms    Petrol
80                                 Mahindra Scorpio S4    Mahindra  2015       8,65,000    30,000 kms    Diesel
81                      Mahindra Scorpio VLX 2WD BS IV    Mahindra  2014       6,99,000    50,000 kms    Diesel
82                                  Mahindra Quanto C8    Mahindra  2013       3,75,000    20,000 kms    Diesel
83                                       Ford EcoSport        Ford  2017       4,89,999    39,000 kms    Petrol
84                                          Honda Brio       Honda  2012       2,24,999    30,000 kms    Petrol
86        Volkswagen Vento Highline Plus 1.5 Diesel AT  Volkswagen  2019      12,00,000     3,600 kms    Diesel
87                                   Hyundai i20 Magna     Hyundai  2009       1,95,000    32,000 kms    Petrol
88                    Toyota Corolla Altis Diesel D4DG      Toyota  2010       3,51,000    38,000 kms    Diesel
89                     Hyundai Verna Transform SX VTVT     Hyundai  2008       1,60,000    45,000 kms    Petrol
90                     Toyota Corolla Altis Petrol Ltd      Toyota  2009       2,40,000    35,000 kms    Petrol
91                              Honda City 1.5 EXi New       Honda  2005         90,000    50,000 kms    Petrol
92                         Hyundai Elite i20 Magna 1.2     Hyundai  2014       4,15,000    32,000 kms    Petrol
93                    Skoda Fabia 1.2L Diesel Elegance       Skoda  2011       1,55,000    45,863 kms    Diesel
94                                   BMW 3 Series 320i         BMW  2011       6,00,000    60,500 kms    Petrol
95                            Maruti Suzuki A Star Lxi      Maruti  2011       1,89,500    12,500 kms    Petrol
96                                     Toyota Etios GD      Toyota  2013       3,50,000    60,000 kms    Diesel
97                         Ford Figo Diesel EXI Option        Ford  2012       2,10,000    35,000 kms    Diesel
98             Maruti Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2014       3,90,000    35,000 kms    Petrol
99                            Chevrolet Beat LT Diesel   Chevrolet  2012       1,35,000    45,000 kms    Diesel
100                           BMW 7 Series 740Li Sedan         BMW  2009      16,00,000    35,000 kms    Petrol
101                        Mahindra XUV500 W8 AWD 2013    Mahindra  2013       7,01,000    38,000 kms    Diesel
102                              Hyundai i10 Magna 1.2     Hyundai  2014       2,65,000    18,000 kms    Petrol
103                          Hyundai Verna Fluidic New     Hyundai  2015       5,25,000    35,000 kms    Diesel
104                  Maruti Suzuki Swift VXi 1.2 BS IV      Maruti  2013       3,72,000    13,349 kms    Petrol
105                      Maruti Suzuki Ertiga ZXI Plus      Maruti  2016       6,35,000    29,000 kms    Petrol
106                   Ford EcoSport Titanium 1.5L TDCi        Ford  2014       5,50,000    44,000 kms    Diesel
107                           Maruti Suzuki Ertiga Vxi      Maruti  2016       5,75,000    29,000 kms    Petrol
108                           Maruti Suzuki Ertiga VDi      Maruti  2013       4,85,000    42,000 kms    Diesel
109                      Maruti Suzuki Alto LXi BS III      Maruti  2012       1,55,000    14,000 kms    Petrol
110                    Hyundai Grand i10 Asta 1.1 CRDi     Hyundai  2014       3,45,000    49,000 kms    Diesel
111                           Honda Amaze 1.2 S i VTEC       Honda  2014       3,25,000    42,000 kms    Petrol
112                  Hyundai i20 Asta 1.4 CRDI 6 Speed     Hyundai  2012       3,29,500    36,200 kms    Diesel
113                               Ford Figo Diesel EXI        Ford  2014       1,95,000    50,000 kms    Diesel
114               Maruti Suzuki Eeco 5 STR WITH AC HTR      Maruti  2015       2,51,111    55,000 kms    Petrol
115                           Maruti Suzuki Ertiga ZXi      Maruti  2014       5,69,999    45,000 kms    Petrol
116                    Maruti Suzuki Esteem LXi BS III      Maruti  2007         69,999    51,000 kms    Petrol
117                             Maruti Suzuki Ritz VXI      Maruti  2014       2,99,999    19,000 kms    Petrol
118                                Maruti Suzuki Dzire      Maruti  2009       2,20,000    46,000 kms    Petrol
119                             Maruti Suzuki Ritz LDi      Maruti  2013       3,99,999    33,000 kms    Diesel
120                  Maruti Suzuki Swift VXi 1.2 BS IV      Maruti  2013       3,72,000    13,349 kms    Petrol
121                            Maruti Suzuki Dzire VDI      Maruti  2015       4,50,000  1,04,000 kms    Diesel
122                                Toyota Etios Liva G      Toyota  2014       2,70,000    55,000 kms    Petrol
123                        Hyundai i20 Sportz 1.4 CRDI     Hyundai  2011       3,50,000    33,333 kms    Diesel
124                                    Chevrolet Spark   Chevrolet  2012       1,58,400    33,600 kms    Petrol
125                     Maruti Suzuki Alto K10 VXi AMT      Maruti  2017       3,50,000     5,600 kms    Petrol
126                                    Nissan Micra XV      Nissan  2011       1,79,000    41,000 kms    Petrol
127                                Maruti Suzuki Swift      Maruti  2007       1,25,000    70,000 kms    Petrol
128                             Maruti Suzuki Alto 800      Maruti  2018       2,00,000     7,500 kms    Petrol
129                           Honda Amaze 1.5 S i DTEC       Honda  2013       2,99,000    45,000 kms    Diesel
130                         Maruti Suzuki Alto 800 Vxi      Maruti  2015       2,20,000    38,000 kms    Petrol
131                                     Chevrolet Beat   Chevrolet  2015       1,50,000    30,000 kms    Petrol
133                                Honda City 1.5 V MT       Honda  2010       2,85,000    35,000 kms    Petrol
134                      Ford EcoSport Trend 1.5L TDCi        Ford  2016       8,30,000    24,330 kms    Diesel
135                               Hyundai i20 Asta 1.2     Hyundai  2009       2,10,000    65,480 kms    Petrol
136            Maruti Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2013       3,40,000    41,000 kms    Petrol
137                                 Tata Indica V2 eLS        Tata  2006         90,000    20,000 kms    Petrol
138                         Maruti Suzuki Alto 800 Lxi      Maruti  2018  Ask For Price    28,028 kms    Petrol
139                        Hindustan Motors Ambassador   Hindustan  2000         70,000  2,00,000 kms    Diesel
140                        Toyota Corolla Altis 1.8 GL      Toyota  2010       2,89,999    70,000 kms    Petrol
141                         Toyota Corolla Altis 1.8 J      Toyota  2012       3,49,999    59,000 kms    Petrol
142                   Toyota Innova 2.5 GX BS IV 7 STR      Toyota  2012       8,49,999    99,000 kms    Diesel
143                   Volkswagen Jetta Highline TDI AT  Volkswagen  2014       7,49,999    46,000 kms    Diesel
144                 Volkswagen Polo Comfortline 1.2L P  Volkswagen  2015       3,99,999     2,800 kms    Petrol
145                                    Volkswagen Polo  Volkswagen  2014       2,74,999    32,000 kms    Petrol
146                                   Mahindra Scorpio    Mahindra  2015       9,84,999    22,000 kms    Diesel
147                                     Renault Duster     Renault  2014       4,49,999    50,000 kms    Diesel
148                                        Honda Amaze       Honda  2015       3,44,999    22,000 kms    Petrol
149                                       Nissan Sunny      Nissan  2012       2,24,999    45,000 kms    Petrol
150                                  Hyundai Elite i20     Hyundai  2018       5,99,999    21,000 kms    Petrol
151                                       Renault Kwid     Renault  2016       2,44,999    11,000 kms    Petrol
152                                     Renault Duster     Renault  2013       3,99,999    41,000 kms    Diesel
153                                      Ford EcoSport        Ford  2017       4,89,999    39,000 kms    Petrol
154                                     Renault Duster     Renault  2014       4,74,999    50,000 kms    Diesel
155                        Mahindra Scorpio VLX Airbag    Mahindra  2011       4,99,999    66,000 kms    Diesel
156                         Maruti Suzuki Alto 800 Lxi      Maruti  2018       3,10,000     3,000 kms    Petrol
157                             Chevrolet Spark LT 1.0   Chevrolet  2010         85,000    45,000 kms    Petrol
158                                 Datsun Redi GO T O      Datsun  2016       2,45,000     7,000 kms    Petrol
159                         Maruti Suzuki Swift RS VDI      Maruti  2010       1,89,500    38,500 kms    Diesel
160                             Fiat Punto Emotion 1.2        Fiat  2012       1,69,500    37,200 kms    Diesel
161                         Maruti Suzuki Swift RS VDI      Maruti  2010       1,59,500    43,200 kms    Diesel
162                                    Toyota Etios GD      Toyota  2013       2,75,000    24,800 kms    Petrol
163                        Hyundai i20 Sportz 1.4 CRDI     Hyundai  2014       3,70,000    60,000 kms    Diesel
164                             Hyundai i10 Sportz 1.2     Hyundai  2010       1,68,000    45,872 kms    Petrol
165                       Chevrolet Beat LT Opt Diesel   Chevrolet  2011       1,50,000    40,000 kms    Diesel
166                           Chevrolet Beat LS Diesel   Chevrolet  2011       1,45,000    45,000 kms    Diesel
167                           Chevrolet Beat LT Diesel   Chevrolet  2012         98,500    38,000 kms    Diesel
168                     Mahindra Scorpio VLX 2WD BS IV    Mahindra  2014       6,99,000    50,000 kms    Diesel
169                                     Tata Indigo CS        Tata  2011         85,000    11,400 kms    Diesel
170                         Toyota Corolla Altis 1.8 J      Toyota  2015       5,75,000    42,000 kms    Petrol
171                                Honda City 1.5 V MT       Honda  2014       5,49,000    39,000 kms    Petrol
172                            Maruti Suzuki Swift VDi      Maruti  2011       2,09,000    47,000 kms    Diesel
173                               Hyundai Eon Era Plus     Hyundai  2013       1,85,000    27,000 kms    Petrol
174                               Mahindra Scorpio S10    Mahindra  2015       9,00,000    97,200 kms    Diesel
175                                    Mahindra XUV500    Mahindra  2014       6,99,999    52,000 kms    Diesel
176                                         Honda Brio       Honda  2012       2,24,999    30,000 kms    Petrol
177                                        Ford Fiesta        Ford  2011       2,74,999    55,000 kms    Diesel
178                                        Honda Amaze       Honda  2013       2,84,999    46,000 kms    Diesel
179                                         Honda City       Honda  2015       5,99,999    30,000 kms    Diesel

In [10]:
# for price
ds['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,85,000', '3,40,000', '70,000',
       '2,89,999', '8,49,999', '7,49,999', '2,74,999', '9,84,999',
       '5,99,999', '2,44,999', '4,74,999', '2,45,000', '1,69,500',
       '2,75,000', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

In [11]:
ds['Price']= ds['Price'].str.replace(',','')

In [12]:
ds['Price']= pd.to_numeric(ds['Price'], errors='coerce')

In [13]:
ds['Price'].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  285000.,  340000.,   70000.,
        289999.,  849999.,  749999.,  274999.,  984999.,  599999.,
        244999.,  474999.,  245000.,  169500.,  275000.,  370000.,
        168000.,  145000.,   98500.,  209000.,  185000.,  900000.,
        699999.,  199999.,  544999.,  199000.,  540000.,   49000.,
        700000.,   55000.,  895000.,  355000.,  565000.,  365000.,
         40000.,  400000.,  330000.,  580000.,  379000.,  219000.,
        519000.,  730000., 2000000., 2100000., 1400000.,  311000.,
        855000.,  535000.,  178000.,  300000.,  255000.,  549999.,
        380000.,   57000.,  410000.,  225000.,  120000.,   59000.,
        599000.,  675000.,   72500.,  610000.,  230000.,  520000.,
        524999.,  424999.,  644999.,  584999.,  799999.,  444999.,
        649999.,  944999.,  574999.,  374999.,  130000.,  401000.,
       1350000.,  174999.,  239999.,   99999.,  324999., 1074999.,
       1130000.,  149000.,  770000.,   30000.,  335000.,  399000.,
         65000.,  169999.,  165000.,  560000.,  950000.,  715000.,
         45000.,  940000.,  155555., 1500000.,  495000.,  800000.,
       1299000.,  530000., 1499000.,   32000.,  405000.,  760000.,
        750000.,  419000.,  140000., 1540000.,  123000.,  498000.,
        480000.,  488000., 1525000.,  548900.,  725000.,   99000.,
         52000., 2800000.,  499000.,  381000.,  278000.,  690000.,
        260000.,   90001.,  115000., 1599000.,  159000.,   51999.,
        215000.,   35000., 1150000.,  269000.,   60000.,  430000.,
       8500003.,  401919.,  490000.,  424000.,  205000.,  549900.,
        435000.,  189700.,  389700.,  360000.,  295000.,  114990.,
       1065000.,  470000.,   48000.,  188000.,  465000.,  179999.,
       2190000., 2390000., 1075000.,  475000., 1025000.,  615000.,
       1900000., 1490000., 1510000., 1850000.,  790000., 1725000.,
       1225000.,   68000.,  970000., 3100000.,  899000.,   88000.,
         53000.,  568500.,   71000.,  590000.,  795000.,   42000.,
        189000.,  162000.,   35999., 2900000.,   39999.,   50500.,
        510000.,  860000.,  500001.])

In [14]:

ds['kms_driven'] = ds['kms_driven'].str.replace(',','').str.replace(' kms','')

In [15]:
ds['kms_driven']= pd.to_numeric(ds['kms_driven'], errors='coerce')

In [16]:
#to remove outliers to kns_driven
ds= ds[ds['kms_driven'] >= 10000]
ds= ds[ds['kms_driven'] <= 200000]

In [17]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 751 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        751 non-null    object
 1   company     751 non-null    object
 2   year        751 non-null    int64
 3   Price       736 non-null    float64
 4   kms_driven  751 non-null    int64
 5   fuel_type   751 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 41.1+ KB

In [18]:
sorted(ds['kms_driven'].unique())

[np.int64(10000),
 np.int64(10544),
 np.int64(10750),
 np.int64(11000),
 np.int64(11400),
 np.int64(11500),
 np.int64(11523),
 np.int64(12000),
 np.int64(12500),
 np.int64(12516),
 np.int64(13000),
 np.int64(13349),
 np.int64(13500),
 np.int64(13900),
 np.int64(14000),
 np.int64(15000),
 np.int64(15141),
 np.int64(15487),
 np.int64(15574),
 np.int64(15975),
 np.int64(16000),
 np.int64(16934),
 np.int64(18000),
 np.int64(18500),
 np.int64(19000),
 np.int64(19336),
 np.int64(20000),
 np.int64(21000),
 np.int64(22000),
 np.int64(22134),
 np.int64(23000),
 np.int64(23452),
 np.int64(24000),
 np.int64(24330),
 np.int64(24530),
 np.int64(24652),
 np.int64(24695),
 np.int64(24800),
 np.int64(25000),
 np.int64(25500),
 np.int64(26500),
 np.int64(27000),
 np.int64(28000),
 np.int64(28028),
 np.int64(28400),
 np.int64(28600),
 np.int64(29000),
 np.int64(29500),
 np.int64(29685),
 np.int64(30000),
 np.int64(30201),
 np.int64(30600),
 np.int64(30874),
 np.int64(31000),
 np.int64(32000),
 np.int64(32700),
 np.int64(33000),
 np.int64(33333),
 np.int64(33400),
 np.int64(33600),
 np.int64(34000),
 np.int64(34580),
 np.int64(35000),
 np.int64(35500),
 np.int64(35522),
 np.int64(35550),
 np.int64(36000),
 np.int64(36200),
 np.int64(36469),
 np.int64(37000),
 np.int64(37200),
 np.int64(37458),
 np.int64(37518),
 np.int64(38000),
 np.int64(38200),
 np.int64(38500),
 np.int64(38600),
 np.int64(38900),
 np.int64(39000),
 np.int64(39522),
 np.int64(39700),
 np.int64(40000),
 np.int64(41000),
 np.int64(41800),
 np.int64(42000),
 np.int64(42590),
 np.int64(43000),
 np.int64(43200),
 np.int64(43222),
 np.int64(44000),
 np.int64(44005),
 np.int64(45000),
 np.int64(45863),
 np.int64(45872),
 np.int64(45933),
 np.int64(46000),
 np.int64(47000),
 np.int64(47900),
 np.int64(48000),
 np.int64(48006),
 np.int64(48008),
 np.int64(48247),
 np.int64(48508),
 np.int64(48660),
 np.int64(49000),
 np.int64(49500),
 np.int64(49800),
 np.int64(50000),
 np.int64(51000),
 np.int64(52000),
 np.int64(52500),
 np.int64(52800),
 np.int64(53000),
 np.int64(54000),
 np.int64(54500),
 np.int64(54870),
 np.int64(55000),
 np.int64(55700),
 np.int64(55800),
 np.int64(56000),
 np.int64(56400),
 np.int64(56450),
 np.int64(56758),
 np.int64(57000),
 np.int64(57923),
 np.int64(58000),
 np.int64(58559),
 np.int64(59000),
 np.int64(59466),
 np.int64(59910),
 np.int64(60000),
 np.int64(60105),
 np.int64(60123),
 np.int64(60500),
 np.int64(62000),
 np.int64(62500),
 np.int64(63000),
 np.int64(64000),
 np.int64(65000),
 np.int64(65422),
 np.int64(65480),
 np.int64(66000),
 np.int64(67000),
 np.int64(68000),
 np.int64(68485),
 np.int64(69000),
 np.int64(69900),
 np.int64(70000),
 np.int64(71200),
 np.int64(72000),
 np.int64(72160),
 np.int64(73000),
 np.int64(74000),
 np.int64(75000),
 np.int64(76000),
 np.int64(77000),
 np.int64(80000),
 np.int64(80200),
 np.int64(81876),
 np.int64(82000),
 np.int64(84000),
 np.int64(85000),
 np.int64(85455),
 np.int64(85960),
 np.int64(87000),
 np.int64(88000),
 np.int64(90000),
 np.int64(90001),
 np.int64(91200),
 np.int64(95000),
 np.int64(95500),
 np.int64(97000),
 np.int64(97200),
 np.int64(99000),
 np.int64(100000),
 np.int64(100200),
 np.int64(100800),
 np.int64(102563),
 np.int64(103553),
 np.int64(104000),
 np.int64(111111),
 np.int64(116000),
 np.int64(117000),
 np.int64(120000),
 np.int64(129000),
 np.int64(130000),
 np.int64(131000),
 np.int64(132000),
 np.int64(133000),
 np.int64(137495),
 np.int64(140000),
 np.int64(146000),
 np.int64(147000),
 np.int64(150000),
 np.int64(160000),
 np.int64(166000),
 np.int64(170000),
 np.int64(175400),
 np.int64(175430),
 np.int64(180000),
 np.int64(195000),
 np.int64(200000)]

In [19]:
ds['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [20]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 751 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        751 non-null    object
 1   company     751 non-null    object
 2   year        751 non-null    int64
 3   Price       736 non-null    float64
 4   kms_driven  751 non-null    int64
 5   fuel_type   751 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 41.1+ KB

In [21]:
ds['company'].unique()

array(['Hyundai', 'Maruti', 'Ford', 'Skoda', 'Mahindra', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Mercedes', 'Land', 'Force', 'Jaguar', 'Volvo'], dtype=object)

In [22]:
#remove company names from name column
for i in ds.index:
    company= ds.loc[i,'company']
    name= ds.loc[i,'name']
    name= name.replace(company,'').strip()
    ds.loc[i,'name']= name

In [23]:
print(ds.to_string())

                                         name     company  year      Price  kms_driven fuel_type
0                Santro Xing XO eRLX Euro III     Hyundai  2007    80000.0       45000    Petrol
2                         Suzuki Alto 800 Vxi      Maruti  2018        NaN       22000    Petrol
3              Grand i10 Magna 1.2 Kappa VTVT     Hyundai  2014   325000.0       28000    Petrol
4                 EcoSport Titanium 1.5L TDCi        Ford  2014   575000.0       36000    Diesel
5                 EcoSport Titanium 1.5L TDCi        Ford  2015        NaN       59000    Diesel
6                                        Figo        Ford  2012   175000.0       41000    Diesel
7                                         Eon     Hyundai  2013   190000.0       25000    Petrol
8                 EcoSport Ambiente 1.5L TDCi        Ford  2016   830000.0       24530    Diesel
9                     Suzuki Alto K10 VXi AMT      Maruti  2015   250000.0       60000    Petrol
10                      Fabia Classic 1.2 MPI       Skoda  2010   182000.0       60000    Petrol
11                        Suzuki Stingray VXi      Maruti  2015   315000.0       30000    Petrol
12                        Elite i20 Magna 1.2     Hyundai  2014   415000.0       32000    Petrol
13                          Scorpio SLE BS IV    Mahindra  2015   320000.0       48660    Diesel
14               Santro Xing XO eRLX Euro III     Hyundai  2007    80000.0       45000    Petrol
17                                         Q7        Audi  2014   500000.0       16934    Diesel
18                                Scorpio S10    Mahindra  2016   350000.0       43000    Diesel
19                            Suzuki Alto 800      Maruti  2014   160000.0       35550    Petrol
20                                Scorpio S10    Mahindra  2016   350000.0       43000    Diesel
21                                Scorpio S10    Mahindra  2016   310000.0       39522    Diesel
22                        Suzuki Alto 800 Vxi      Maruti  2015    75000.0       39000    Petrol
23                             i20 Sportz 1.2     Hyundai  2012   100000.0       55000    Petrol
24                             i20 Sportz 1.2     Hyundai  2012   100000.0       55000    Petrol
25                             i20 Sportz 1.2     Hyundai  2012   100000.0       55000    Petrol
26                         Suzuki Alto 800 Lx      Maruti  2017   190000.0       72000    Petrol
27                   Suzuki Vitara Brezza ZDi      Maruti  2016   290000.0       15975    Diesel
28                             Suzuki Alto LX      Maruti  2008    95000.0       70000    Petrol
29                                  Bolero DI    Mahindra  2017   180000.0       23452    Diesel
30                     Suzuki Swift Dzire ZDi      Maruti  2014   385000.0       35522    Diesel
31                            Scorpio S10 4WD    Mahindra  2015   250000.0       48508    Diesel
32                     Suzuki Swift Vdi BSIII      Maruti  2017   180000.0       15487    Petrol
33                  Suzuki Wagon R VXi BS III      Maruti  2013   105000.0       39000    Petrol
34                   Suzuki Wagon R VXi Minor      Maruti  2013   105000.0       39000    Petrol
35                   Innova 2.0 G 8 STR BS IV      Toyota  2012   650000.0       82000    Diesel
36                            Lodgy 85 PS RXL     Renault  2018   689999.0       20000    Diesel
37               Yeti Ambition 2.0 TDI CR 4x2       Skoda  2012   448000.0       68000    Diesel
38                    Suzuki Baleno Delta 1.2      Maruti  2017   549000.0       32000    Diesel
39              Duster 110 PS RxZ Diesel Plus     Renault  2012   501000.0       38000    Diesel
40                    Duster 85 PS RxE Diesel     Renault  2013   489999.0       27000    Diesel
41                              City 1.5 S MT       Honda  2011   280000.0       33000    Petrol
42                    Suzuki Alto K10 VXi AMT      Maruti  2015   250000.0       60000    Petrol
43                               Suzuki Dzire      Maruti  2013   349999.0       46000    Diesel
44                                      Amaze       Honda  2013   284999.0       46000    Diesel
45                        Amaze 1.5 SX i DTEC       Honda  2015   345000.0       36000    Diesel
46                                       City       Honda  2015   499999.0       55000    Petrol
47                                  Redi GO S      Datsun  2017   235000.0       16000    Petrol
48                          Suzuki SX4 ZXI MT      Maruti  2010   249999.0       36000    Petrol
49               Pajero Sport Limited Edition  Mitsubishi  2015  1475000.0       47000    Diesel
50                                  Bolero DI    Mahindra  2017   180000.0       23452    Diesel
51                     Suzuki Swift Dzire ZDi      Maruti  2014   385000.0       35522    Diesel
52                            Scorpio S10 4WD    Mahindra  2015   250000.0       48508    Diesel
53                     Suzuki Swift Vdi BSIII      Maruti  2017   180000.0       15487    Petrol
54                  Suzuki Wagon R VXi BS III      Maruti  2013   105000.0       39000    Petrol
55                   Suzuki Wagon R VXi Minor      Maruti  2013   105000.0       39000    Petrol
56                                Scorpio S10    Mahindra  2015   395000.0       35000    Diesel
57             Suzuki Swift VXi 1.2 ABS BS IV      Maruti  2017   220000.0       30874    Petrol
58                                City ZX CVT       Honda  2017   170000.0       15000    Diesel
59                    Suzuki Wagon R LX BS IV      Maruti  2013    85000.0       29685    Petrol
60                                       Figo        Ford  2012   175000.0       41000    Diesel
61                                        Eon     Hyundai  2013   190000.0       25000    Petrol
62                    Indigo eCS LS CR4 BS IV        Tata  2017   200000.0      130000    Diesel
63                EcoSport Ambiente 1.5L TDCi        Ford  2016   830000.0       24530    Diesel
64                    Indigo eCS LS CR4 BS IV        Tata  2017   200000.0      130000    Diesel
65                          Scorpio SLE BS IV    Mahindra  2012   570000.0       19000    Diesel
66                  Polo Highline Exquisite P  Volkswagen  2014   315000.0       60000    Petrol
67                      Fabia Classic 1.2 MPI       Skoda  2010   182000.0       60000    Petrol
68                        Suzuki Stingray VXi      Maruti  2015   315000.0       30000    Petrol
70                               Spark LS 1.0   Chevrolet  2010   110000.0       41000    Petrol
71                    Duster 110PS Diesel RxZ     Renault  2012   501000.0       35000    Diesel
72                                       City       Honda  2015   448999.0       54000    Petrol
73                               Cooper S 1.6        Mini  2013  1891111.0       13000    Petrol
74                                  Redi GO S      Datsun  2017   235000.0       16000    Petrol
75                 Fabia 1.2L Diesel Ambiente       Skoda  2011   159500.0       38200    Diesel
76                                      Amaze       Honda  2015   344999.0       22000    Petrol
77                                      Amaze       Honda  2015   344999.0       22000    Petrol
78                                     Duster     Renault  2014   449999.0       50000    Diesel
79                               Cooper S 1.6        Mini  2013  1891111.0       13500    Petrol
80                                 Scorpio S4    Mahindra  2015   865000.0       30000    Diesel
81                      Scorpio VLX 2WD BS IV    Mahindra  2014   699000.0       50000    Diesel
82                                  Quanto C8    Mahindra  2013   375000.0       20000    Diesel
83                                   EcoSport        Ford  2017   489999.0       39000    Petrol
84                                       Brio       Honda  2012   224999.0       30000    Petrol
87                                  i20 Magna     Hyundai  2009   195000.0       32000    Petrol
88                  Corolla Altis Diesel D4DG      Toyota  2010   351000.0       38000    Diesel
89                    Verna Transform SX VTVT     Hyundai  2008   160000.0       45000    Petrol
90                   Corolla Altis Petrol Ltd      Toyota  2009   240000.0       35000    Petrol
91                           City 1.5 EXi New       Honda  2005    90000.0       50000    Petrol
92                        Elite i20 Magna 1.2     Hyundai  2014   415000.0       32000    Petrol
93                 Fabia 1.2L Diesel Elegance       Skoda  2011   155000.0       45863    Diesel
94                              3 Series 320i         BMW  2011   600000.0       60500    Petrol
95                          Suzuki A Star Lxi      Maruti  2011   189500.0       12500    Petrol
96                                   Etios GD      Toyota  2013   350000.0       60000    Diesel
97                     Figo Diesel EXI Option        Ford  2012   210000.0       35000    Diesel
98           Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2014   390000.0       35000    Petrol
99                             Beat LT Diesel   Chevrolet  2012   135000.0       45000    Diesel
100                      7 Series 740Li Sedan         BMW  2009  1600000.0       35000    Petrol
101                        XUV500 W8 AWD 2013    Mahindra  2013   701000.0       38000    Diesel
102                             i10 Magna 1.2     Hyundai  2014   265000.0       18000    Petrol
103                         Verna Fluidic New     Hyundai  2015   525000.0       35000    Diesel
104                Suzuki Swift VXi 1.2 BS IV      Maruti  2013   372000.0       13349    Petrol
105                    Suzuki Ertiga ZXI Plus      Maruti  2016   635000.0       29000    Petrol
106               EcoSport Titanium 1.5L TDCi        Ford  2014   550000.0       44000    Diesel
107                         Suzuki Ertiga Vxi      Maruti  2016   575000.0       29000    Petrol
108                         Suzuki Ertiga VDi      Maruti  2013   485000.0       42000    Diesel
109                    Suzuki Alto LXi BS III      Maruti  2012   155000.0       14000    Petrol
110                   Grand i10 Asta 1.1 CRDi     Hyundai  2014   345000.0       49000    Diesel
111                        Amaze 1.2 S i VTEC       Honda  2014   325000.0       42000    Petrol
112                 i20 Asta 1.4 CRDI 6 Speed     Hyundai  2012   329500.0       36200    Diesel
113                           Figo Diesel EXI        Ford  2014   195000.0       50000    Diesel
114             Suzuki Eeco 5 STR WITH AC HTR      Maruti  2015   251111.0       55000    Petrol
115                         Suzuki Ertiga ZXi      Maruti  2014   569999.0       45000    Petrol
116                  Suzuki Esteem LXi BS III      Maruti  2007    69999.0       51000    Petrol
117                           Suzuki Ritz VXI      Maruti  2014   299999.0       19000    Petrol
118                              Suzuki Dzire      Maruti  2009   220000.0       46000    Petrol
119                           Suzuki Ritz LDi      Maruti  2013   399999.0       33000    Diesel
120                Suzuki Swift VXi 1.2 BS IV      Maruti  2013   372000.0       13349    Petrol
121                          Suzuki Dzire VDI      Maruti  2015   450000.0      104000    Diesel
122                              Etios Liva G      Toyota  2014   270000.0       55000    Petrol
123                       i20 Sportz 1.4 CRDI     Hyundai  2011   350000.0       33333    Diesel
124                                     Spark   Chevrolet  2012   158400.0       33600    Petrol
126                                  Micra XV      Nissan  2011   179000.0       41000    Petrol
127                              Suzuki Swift      Maruti  2007   125000.0       70000    Petrol
129                        Amaze 1.5 S i DTEC       Honda  2013   299000.0       45000    Diesel
130                       Suzuki Alto 800 Vxi      Maruti  2015   220000.0       38000    Petrol
131                                      Beat   Chevrolet  2015   150000.0       30000    Petrol
133                             City 1.5 V MT       Honda  2010   285000.0       35000    Petrol
134                  EcoSport Trend 1.5L TDCi        Ford  2016   830000.0       24330    Diesel
135                              i20 Asta 1.2     Hyundai  2009   210000.0       65480    Petrol
136          Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2013   340000.0       41000    Petrol
137                             Indica V2 eLS        Tata  2006    90000.0       20000    Petrol
138                       Suzuki Alto 800 Lxi      Maruti  2018        NaN       28028    Petrol
139                         Motors Ambassador   Hindustan  2000    70000.0      200000    Diesel
140                      Corolla Altis 1.8 GL      Toyota  2010   289999.0       70000    Petrol
141                       Corolla Altis 1.8 J      Toyota  2012   349999.0       59000    Petrol
142                 Innova 2.5 GX BS IV 7 STR      Toyota  2012   849999.0       99000    Diesel
143                     Jetta Highline TDI AT  Volkswagen  2014   749999.0       46000    Diesel
145                                      Polo  Volkswagen  2014   274999.0       32000    Petrol
146                                   Scorpio    Mahindra  2015   984999.0       22000    Diesel
147                                    Duster     Renault  2014   449999.0       50000    Diesel
148                                     Amaze       Honda  2015   344999.0       22000    Petrol
149                                     Sunny      Nissan  2012   224999.0       45000    Petrol
150                                 Elite i20     Hyundai  2018   599999.0       21000    Petrol
151                                      Kwid     Renault  2016   244999.0       11000    Petrol
152                                    Duster     Renault  2013   399999.0       41000    Diesel
153                                  EcoSport        Ford  2017   489999.0       39000    Petrol
154                                    Duster     Renault  2014   474999.0       50000    Diesel
155                        Scorpio VLX Airbag    Mahindra  2011   499999.0       66000    Diesel
157                              Spark LT 1.0   Chevrolet  2010    85000.0       45000    Petrol
159                       Suzuki Swift RS VDI      Maruti  2010   189500.0       38500    Diesel
160                         Punto Emotion 1.2        Fiat  2012   169500.0       37200    Diesel
161                       Suzuki Swift RS VDI      Maruti  2010   159500.0       43200    Diesel
162                                  Etios GD      Toyota  2013   275000.0       24800    Petrol
163                       i20 Sportz 1.4 CRDI     Hyundai  2014   370000.0       60000    Diesel
164                            i10 Sportz 1.2     Hyundai  2010   168000.0       45872    Petrol
165                        Beat LT Opt Diesel   Chevrolet  2011   150000.0       40000    Diesel
166                            Beat LS Diesel   Chevrolet  2011   145000.0       45000    Diesel
167                            Beat LT Diesel   Chevrolet  2012    98500.0       38000    Diesel
168                     Scorpio VLX 2WD BS IV    Mahindra  2014   699000.0       50000    Diesel
169                                 Indigo CS        Tata  2011    85000.0       11400    Diesel
170                       Corolla Altis 1.8 J      Toyota  2015   575000.0       42000    Petrol
171                             City 1.5 V MT       Honda  2014   549000.0       39000    Petrol
172                          Suzuki Swift VDi      Maruti  2011   209000.0       47000    Diesel
173                              Eon Era Plus     Hyundai  2013   185000.0       27000    Petrol
174                               Scorpio S10    Mahindra  2015   900000.0       97200    Diesel
175                                    XUV500    Mahindra  2014   699999.0       52000    Diesel
176                                      Brio       Honda  2012   224999.0       30000    Petrol
177                                    Fiesta        Ford  2011   274999.0       55000    Diesel
178                                     Amaze       Honda  2013   284999.0       46000    Diesel
179                                      City       Honda  2015   599999.0       30000    Diesel
180                            Suzuki Wagon R      Maruti  2012   199999.0       44000    Petrol
181                                      City       Honda  2014   544999.0       45000    Diesel
182                                       i20     Hyundai  2009   199000.0       31000    Petrol
183                  Indigo eCS LX TDI BS III        Tata  2016   320000.0      175430    Diesel
184                 Fluidic Verna 1.6 CRDi SX     Hyundai  2015   540000.0       38000    Diesel
186                                 Quanto C8    Mahindra  2013   340000.0       37000    Diesel
187                          Petra ELX 1.2 PS        Fiat  2008    75000.0       65000    Petrol
188                Fabia 1.2L Diesel Ambiente       Skoda  2011   159500.0       38200    Diesel
189                              Cooper S 1.6        Mini  2013  1891111.0       13000    Petrol
192                             Suzuki Zen VX      Maruti  2000    55000.0       60000    Petrol
193                                      City       Honda  2015   448999.0       54000    Petrol
194                  Creta 1.6 SX Plus Petrol     Hyundai  2017   895000.0       32000    Petrol
196                               Scorpio SLX    Mahindra  2007   355000.0       75000    Diesel
197                         Scorpio SLE BS IV    Mahindra  2012   565000.0       62000    Diesel
198                 Innova 2.5 G BS III 8 STR      Toyota  2006   365000.0       73000    Diesel
199                   Suzuki Alto K10 VXi AMT      Maruti  2011   145000.0       41000    Petrol
200                  Suzuki Wagon R LXI BS IV      Maruti  2011   210000.0       35000    Petrol
202                     Suzuki Alto Std BS IV      Maruti  2013   125000.0       39000    Petrol
203                 Suzuki Wagon R LXi BS III      Maruti  2009   135000.0       45000    Petrol
204                    Suzuki Swift VXI BSIII      Maruti  2006   135000.0       45000    Petrol
205           Sumo Victa EX 10 by 7 Str BSIII        Tata  2012   285000.0       65000    Diesel
207                 Suzuki Wagon R LXi BS III      Maruti  2010   145000.0       54870    Petrol
208                    Suzuki Alto LXi BS III      Maruti  2010   135000.0       34580    Petrol
209              Passat Diesel Comfortline AT  Volkswagen  2009   450000.0       97000    Diesel
210               Scala RxL Diesel Travelogue     Renault  2015   375000.0       25000    Diesel
211                                 Quanto C8    Mahindra  2013   375000.0       20000    Diesel
212         Grand i10 Sportz O 1.2 Kappa VTVT     Hyundai  2014   365000.0       20000    Petrol
213                         i20 Active 1.2 SX     Hyundai  2015   500000.0       18000    Petrol
214                                   Xylo E4    Mahindra  2012   400000.0       35000    Diesel
216                   Duster 110PS Diesel RxZ     Renault  2012   501000.0       35000    Diesel
217                          Bolero SLE BS IV    Mahindra  2013   330000.0       80200    Diesel
219                                Suzuki SX4      Maruti  2012   265000.0       46000    Diesel
223                                     Etios      Toyota  2011   275000.0       36000    Diesel
224                                      Polo  Volkswagen  2015   330000.0       38000    Diesel
225                              City ZX VTEC       Honda  2008   110000.0       45000    Petrol
226                  Suzuki Wagon R LX BS III      Maruti  2006    80000.0       71200    Petrol
227                       City VX O MT Diesel       Honda  2016   519000.0       52000    Diesel

In [24]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 751 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        751 non-null    object
 1   company     751 non-null    object
 2   year        751 non-null    int64
 3   Price       736 non-null    float64
 4   kms_driven  751 non-null    int64
 5   fuel_type   751 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 57.2+ KB

In [25]:
sorted(ds['year'].unique())

[np.int64(1995),
 np.int64(2000),
 np.int64(2001),
 np.int64(2002),
 np.int64(2003),
 np.int64(2004),
 np.int64(2005),
 np.int64(2006),
 np.int64(2007),
 np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018)]

In [26]:
ds.duplicated().sum()

np.int64(85)

In [27]:
ds.drop_duplicates(inplace=True)

In [28]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 666 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        666 non-null    object
 1   company     666 non-null    object
 2   year        666 non-null    int64
 3   Price       651 non-null    float64
 4   kms_driven  666 non-null    int64
 5   fuel_type   666 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 36.4+ KB

In [29]:
ds['Price'].isnull().sum()

np.int64(15)

In [30]:
ds= ds.dropna(subset= ['Price'])

In [31]:
print(ds.to_string())

                                         name     company  year      Price  kms_driven fuel_type
0                Santro Xing XO eRLX Euro III     Hyundai  2007    80000.0       45000    Petrol
3              Grand i10 Magna 1.2 Kappa VTVT     Hyundai  2014   325000.0       28000    Petrol
4                 EcoSport Titanium 1.5L TDCi        Ford  2014   575000.0       36000    Diesel
6                                        Figo        Ford  2012   175000.0       41000    Diesel
7                                         Eon     Hyundai  2013   190000.0       25000    Petrol
8                 EcoSport Ambiente 1.5L TDCi        Ford  2016   830000.0       24530    Diesel
9                     Suzuki Alto K10 VXi AMT      Maruti  2015   250000.0       60000    Petrol
10                      Fabia Classic 1.2 MPI       Skoda  2010   182000.0       60000    Petrol
11                        Suzuki Stingray VXi      Maruti  2015   315000.0       30000    Petrol
12                        Elite i20 Magna 1.2     Hyundai  2014   415000.0       32000    Petrol
13                          Scorpio SLE BS IV    Mahindra  2015   320000.0       48660    Diesel
17                                         Q7        Audi  2014   500000.0       16934    Diesel
18                                Scorpio S10    Mahindra  2016   350000.0       43000    Diesel
19                            Suzuki Alto 800      Maruti  2014   160000.0       35550    Petrol
21                                Scorpio S10    Mahindra  2016   310000.0       39522    Diesel
22                        Suzuki Alto 800 Vxi      Maruti  2015    75000.0       39000    Petrol
23                             i20 Sportz 1.2     Hyundai  2012   100000.0       55000    Petrol
26                         Suzuki Alto 800 Lx      Maruti  2017   190000.0       72000    Petrol
27                   Suzuki Vitara Brezza ZDi      Maruti  2016   290000.0       15975    Diesel
28                             Suzuki Alto LX      Maruti  2008    95000.0       70000    Petrol
29                                  Bolero DI    Mahindra  2017   180000.0       23452    Diesel
30                     Suzuki Swift Dzire ZDi      Maruti  2014   385000.0       35522    Diesel
31                            Scorpio S10 4WD    Mahindra  2015   250000.0       48508    Diesel
32                     Suzuki Swift Vdi BSIII      Maruti  2017   180000.0       15487    Petrol
33                  Suzuki Wagon R VXi BS III      Maruti  2013   105000.0       39000    Petrol
34                   Suzuki Wagon R VXi Minor      Maruti  2013   105000.0       39000    Petrol
35                   Innova 2.0 G 8 STR BS IV      Toyota  2012   650000.0       82000    Diesel
36                            Lodgy 85 PS RXL     Renault  2018   689999.0       20000    Diesel
37               Yeti Ambition 2.0 TDI CR 4x2       Skoda  2012   448000.0       68000    Diesel
38                    Suzuki Baleno Delta 1.2      Maruti  2017   549000.0       32000    Diesel
39              Duster 110 PS RxZ Diesel Plus     Renault  2012   501000.0       38000    Diesel
40                    Duster 85 PS RxE Diesel     Renault  2013   489999.0       27000    Diesel
41                              City 1.5 S MT       Honda  2011   280000.0       33000    Petrol
43                               Suzuki Dzire      Maruti  2013   349999.0       46000    Diesel
44                                      Amaze       Honda  2013   284999.0       46000    Diesel
45                        Amaze 1.5 SX i DTEC       Honda  2015   345000.0       36000    Diesel
46                                       City       Honda  2015   499999.0       55000    Petrol
47                                  Redi GO S      Datsun  2017   235000.0       16000    Petrol
48                          Suzuki SX4 ZXI MT      Maruti  2010   249999.0       36000    Petrol
49               Pajero Sport Limited Edition  Mitsubishi  2015  1475000.0       47000    Diesel
56                                Scorpio S10    Mahindra  2015   395000.0       35000    Diesel
57             Suzuki Swift VXi 1.2 ABS BS IV      Maruti  2017   220000.0       30874    Petrol
58                                City ZX CVT       Honda  2017   170000.0       15000    Diesel
59                    Suzuki Wagon R LX BS IV      Maruti  2013    85000.0       29685    Petrol
62                    Indigo eCS LS CR4 BS IV        Tata  2017   200000.0      130000    Diesel
65                          Scorpio SLE BS IV    Mahindra  2012   570000.0       19000    Diesel
66                  Polo Highline Exquisite P  Volkswagen  2014   315000.0       60000    Petrol
70                               Spark LS 1.0   Chevrolet  2010   110000.0       41000    Petrol
71                    Duster 110PS Diesel RxZ     Renault  2012   501000.0       35000    Diesel
72                                       City       Honda  2015   448999.0       54000    Petrol
73                               Cooper S 1.6        Mini  2013  1891111.0       13000    Petrol
75                 Fabia 1.2L Diesel Ambiente       Skoda  2011   159500.0       38200    Diesel
76                                      Amaze       Honda  2015   344999.0       22000    Petrol
78                                     Duster     Renault  2014   449999.0       50000    Diesel
79                               Cooper S 1.6        Mini  2013  1891111.0       13500    Petrol
80                                 Scorpio S4    Mahindra  2015   865000.0       30000    Diesel
81                      Scorpio VLX 2WD BS IV    Mahindra  2014   699000.0       50000    Diesel
82                                  Quanto C8    Mahindra  2013   375000.0       20000    Diesel
83                                   EcoSport        Ford  2017   489999.0       39000    Petrol
84                                       Brio       Honda  2012   224999.0       30000    Petrol
87                                  i20 Magna     Hyundai  2009   195000.0       32000    Petrol
88                  Corolla Altis Diesel D4DG      Toyota  2010   351000.0       38000    Diesel
89                    Verna Transform SX VTVT     Hyundai  2008   160000.0       45000    Petrol
90                   Corolla Altis Petrol Ltd      Toyota  2009   240000.0       35000    Petrol
91                           City 1.5 EXi New       Honda  2005    90000.0       50000    Petrol
93                 Fabia 1.2L Diesel Elegance       Skoda  2011   155000.0       45863    Diesel
94                              3 Series 320i         BMW  2011   600000.0       60500    Petrol
95                          Suzuki A Star Lxi      Maruti  2011   189500.0       12500    Petrol
96                                   Etios GD      Toyota  2013   350000.0       60000    Diesel
97                     Figo Diesel EXI Option        Ford  2012   210000.0       35000    Diesel
98           Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2014   390000.0       35000    Petrol
99                             Beat LT Diesel   Chevrolet  2012   135000.0       45000    Diesel
100                      7 Series 740Li Sedan         BMW  2009  1600000.0       35000    Petrol
101                        XUV500 W8 AWD 2013    Mahindra  2013   701000.0       38000    Diesel
102                             i10 Magna 1.2     Hyundai  2014   265000.0       18000    Petrol
103                         Verna Fluidic New     Hyundai  2015   525000.0       35000    Diesel
104                Suzuki Swift VXi 1.2 BS IV      Maruti  2013   372000.0       13349    Petrol
105                    Suzuki Ertiga ZXI Plus      Maruti  2016   635000.0       29000    Petrol
106               EcoSport Titanium 1.5L TDCi        Ford  2014   550000.0       44000    Diesel
107                         Suzuki Ertiga Vxi      Maruti  2016   575000.0       29000    Petrol
108                         Suzuki Ertiga VDi      Maruti  2013   485000.0       42000    Diesel
109                    Suzuki Alto LXi BS III      Maruti  2012   155000.0       14000    Petrol
110                   Grand i10 Asta 1.1 CRDi     Hyundai  2014   345000.0       49000    Diesel
111                        Amaze 1.2 S i VTEC       Honda  2014   325000.0       42000    Petrol
112                 i20 Asta 1.4 CRDI 6 Speed     Hyundai  2012   329500.0       36200    Diesel
113                           Figo Diesel EXI        Ford  2014   195000.0       50000    Diesel
114             Suzuki Eeco 5 STR WITH AC HTR      Maruti  2015   251111.0       55000    Petrol
115                         Suzuki Ertiga ZXi      Maruti  2014   569999.0       45000    Petrol
116                  Suzuki Esteem LXi BS III      Maruti  2007    69999.0       51000    Petrol
117                           Suzuki Ritz VXI      Maruti  2014   299999.0       19000    Petrol
118                              Suzuki Dzire      Maruti  2009   220000.0       46000    Petrol
119                           Suzuki Ritz LDi      Maruti  2013   399999.0       33000    Diesel
121                          Suzuki Dzire VDI      Maruti  2015   450000.0      104000    Diesel
122                              Etios Liva G      Toyota  2014   270000.0       55000    Petrol
123                       i20 Sportz 1.4 CRDI     Hyundai  2011   350000.0       33333    Diesel
124                                     Spark   Chevrolet  2012   158400.0       33600    Petrol
126                                  Micra XV      Nissan  2011   179000.0       41000    Petrol
127                              Suzuki Swift      Maruti  2007   125000.0       70000    Petrol
129                        Amaze 1.5 S i DTEC       Honda  2013   299000.0       45000    Diesel
130                       Suzuki Alto 800 Vxi      Maruti  2015   220000.0       38000    Petrol
131                                      Beat   Chevrolet  2015   150000.0       30000    Petrol
133                             City 1.5 V MT       Honda  2010   285000.0       35000    Petrol
134                  EcoSport Trend 1.5L TDCi        Ford  2016   830000.0       24330    Diesel
135                              i20 Asta 1.2     Hyundai  2009   210000.0       65480    Petrol
136          Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2013   340000.0       41000    Petrol
137                             Indica V2 eLS        Tata  2006    90000.0       20000    Petrol
139                         Motors Ambassador   Hindustan  2000    70000.0      200000    Diesel
140                      Corolla Altis 1.8 GL      Toyota  2010   289999.0       70000    Petrol
141                       Corolla Altis 1.8 J      Toyota  2012   349999.0       59000    Petrol
142                 Innova 2.5 GX BS IV 7 STR      Toyota  2012   849999.0       99000    Diesel
143                     Jetta Highline TDI AT  Volkswagen  2014   749999.0       46000    Diesel
145                                      Polo  Volkswagen  2014   274999.0       32000    Petrol
146                                   Scorpio    Mahindra  2015   984999.0       22000    Diesel
149                                     Sunny      Nissan  2012   224999.0       45000    Petrol
150                                 Elite i20     Hyundai  2018   599999.0       21000    Petrol
151                                      Kwid     Renault  2016   244999.0       11000    Petrol
152                                    Duster     Renault  2013   399999.0       41000    Diesel
154                                    Duster     Renault  2014   474999.0       50000    Diesel
155                        Scorpio VLX Airbag    Mahindra  2011   499999.0       66000    Diesel
157                              Spark LT 1.0   Chevrolet  2010    85000.0       45000    Petrol
159                       Suzuki Swift RS VDI      Maruti  2010   189500.0       38500    Diesel
160                         Punto Emotion 1.2        Fiat  2012   169500.0       37200    Diesel
161                       Suzuki Swift RS VDI      Maruti  2010   159500.0       43200    Diesel
162                                  Etios GD      Toyota  2013   275000.0       24800    Petrol
163                       i20 Sportz 1.4 CRDI     Hyundai  2014   370000.0       60000    Diesel
164                            i10 Sportz 1.2     Hyundai  2010   168000.0       45872    Petrol
165                        Beat LT Opt Diesel   Chevrolet  2011   150000.0       40000    Diesel
166                            Beat LS Diesel   Chevrolet  2011   145000.0       45000    Diesel
167                            Beat LT Diesel   Chevrolet  2012    98500.0       38000    Diesel
169                                 Indigo CS        Tata  2011    85000.0       11400    Diesel
170                       Corolla Altis 1.8 J      Toyota  2015   575000.0       42000    Petrol
171                             City 1.5 V MT       Honda  2014   549000.0       39000    Petrol
172                          Suzuki Swift VDi      Maruti  2011   209000.0       47000    Diesel
173                              Eon Era Plus     Hyundai  2013   185000.0       27000    Petrol
174                               Scorpio S10    Mahindra  2015   900000.0       97200    Diesel
175                                    XUV500    Mahindra  2014   699999.0       52000    Diesel
177                                    Fiesta        Ford  2011   274999.0       55000    Diesel
179                                      City       Honda  2015   599999.0       30000    Diesel
180                            Suzuki Wagon R      Maruti  2012   199999.0       44000    Petrol
181                                      City       Honda  2014   544999.0       45000    Diesel
182                                       i20     Hyundai  2009   199000.0       31000    Petrol
183                  Indigo eCS LX TDI BS III        Tata  2016   320000.0      175430    Diesel
184                 Fluidic Verna 1.6 CRDi SX     Hyundai  2015   540000.0       38000    Diesel
186                                 Quanto C8    Mahindra  2013   340000.0       37000    Diesel
187                          Petra ELX 1.2 PS        Fiat  2008    75000.0       65000    Petrol
192                             Suzuki Zen VX      Maruti  2000    55000.0       60000    Petrol
194                  Creta 1.6 SX Plus Petrol     Hyundai  2017   895000.0       32000    Petrol
196                               Scorpio SLX    Mahindra  2007   355000.0       75000    Diesel
197                         Scorpio SLE BS IV    Mahindra  2012   565000.0       62000    Diesel
198                 Innova 2.5 G BS III 8 STR      Toyota  2006   365000.0       73000    Diesel
199                   Suzuki Alto K10 VXi AMT      Maruti  2011   145000.0       41000    Petrol
200                  Suzuki Wagon R LXI BS IV      Maruti  2011   210000.0       35000    Petrol
202                     Suzuki Alto Std BS IV      Maruti  2013   125000.0       39000    Petrol
203                 Suzuki Wagon R LXi BS III      Maruti  2009   135000.0       45000    Petrol
204                    Suzuki Swift VXI BSIII      Maruti  2006   135000.0       45000    Petrol
205           Sumo Victa EX 10 by 7 Str BSIII        Tata  2012   285000.0       65000    Diesel
207                 Suzuki Wagon R LXi BS III      Maruti  2010   145000.0       54870    Petrol
208                    Suzuki Alto LXi BS III      Maruti  2010   135000.0       34580    Petrol
209              Passat Diesel Comfortline AT  Volkswagen  2009   450000.0       97000    Diesel
210               Scala RxL Diesel Travelogue     Renault  2015   375000.0       25000    Diesel
212         Grand i10 Sportz O 1.2 Kappa VTVT     Hyundai  2014   365000.0       20000    Petrol
213                         i20 Active 1.2 SX     Hyundai  2015   500000.0       18000    Petrol
214                                   Xylo E4    Mahindra  2012   400000.0       35000    Diesel
217                          Bolero SLE BS IV    Mahindra  2013   330000.0       80200    Diesel
219                                Suzuki SX4      Maruti  2012   265000.0       46000    Diesel
223                                     Etios      Toyota  2011   275000.0       36000    Diesel
224                                      Polo  Volkswagen  2015   330000.0       38000    Diesel
225                              City ZX VTEC       Honda  2008   110000.0       45000    Petrol
226                  Suzuki Wagon R LX BS III      Maruti  2006    80000.0       71200    Petrol
227                       City VX O MT Diesel       Honda  2016   519000.0       52000    Diesel
228                          Thar CRDe 4x4 AC    Mahindra  2016   730000.0       29000    Diesel
230      A4 1.8 TFSI Multitronic Premium Plus        Audi  2009   699000.0       47000    Petrol
231              Benz GLA Class 200 CDI Sport    Mercedes  2015  2000000.0       20000    Diesel
232                     Rover Freelander 2 SE        Land  2015  2100000.0       30000    Diesel
234                         Aria Pleasure 4X2        Tata  2014   390000.0       35000    Diesel
235                  Benz B Class B180 Sports    Mercedes  2014  1400000.0       31000    Petrol
238                  Indigo eCS LX TDI BS III        Tata  2016   320000.0      175400    Diesel
239                                Jazz VX MT       Honda  2016   450000.0       41000    Petrol
240                        Amaze 1.2 S i VTEC       Honda  2014   311000.0       33000    Petrol
242                                      City       Honda  2012   399999.0       45000    Petrol
243                                      City       Honda  2015   599999.0       39000    Diesel
247                                Scorpio S4    Mahindra  2015   855000.0       30000    Diesel
248                      i20 Active 1.4L SX O     Hyundai  2015   535000.0       37000    Diesel
249                                  Cooper S        Mini  2013  1891111.0       13000    Petrol
250                      Suzuki Ciaz ZXI Plus      Maruti  2017   699000.0       14000    Petrol
251                                Tavera Neo   Chevrolet  2013   375000.0       55000    Diesel
253                                Eon Sportz     Hyundai  2012   178000.0       30000    Petrol
254                  Sumo Gold Select Variant        Tata  2013   300000.0       50000    Diesel
255                        Suzuki Wagon R 1.0      Maruti  2003    90000.0       45000    Petrol
256                  Suzuki Esteem VXi BS III      Maruti  2006    95000.0       45000    Petrol
258                        Enjoy 1.4 LS 8 STR   Chevrolet  2013   245000.0       55000    Diesel
268                    Suzuki Wagon R 1.0 VXi      Maruti  2015   289999.0       22000    Petrol
270                         Terrano XL D Plus      Nissan  2015   499999.0       60000    Diesel
272                   Duster 85 PS RxE Diesel     Renault  2014   489999.0       59000    Diesel
273                   Duster 85 PS RxL Diesel     Renault  2015   549999.0       19000    Diesel
274                          Suzuki Dzire ZXI      Maruti  2013   380000.0       30000    Petrol
275                              Kwid RXT Opt     Renault  2018   325000.0       15000    Petrol
276                           Suzuki  800 Std      Maruti  2003    57000.0       56758    Petrol
277                          Kwid 1.0 RXT AMT     Renault  2018   349999.0       10000    Petrol
279                          Scala RxL Diesel     Renault  2014   349999.0       49000    Diesel
280           Grand i10 Asta 1.2 Kappa VTVT O     Hyundai  2014   410000.0       41000    Petrol
281          Suzuki Swift Dzire VXi 1.2 BS IV      Maruti  2011   225000.0       45000    Petrol
282                            Beat LS Petrol   Chevrolet  2010   120000.0       43000    Petrol
284              Santro Xing XO eRLX Euro III     Hyundai  2000    59000.0       56450    Petrol
287                            Beat LS Petrol   Chevrolet  2010    80000.0       56000    Petrol

In [32]:
ds.to_csv('new_cleaned_data.csv')